src/cart/urls.py
from django.urls import path 

from cart.views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    update_transaction_records,
    # success
)

app_name = 'cart'

urlpatterns = [
    path('addtocart/<int:item_id>' , add_to_cart , name="add_to_cart"),
    path('ordersummary' , order_details , name="order_summary"),
    path('delete/<int:item_id>' , delete_from_cart , name="delete"),
    path('checkout/' , checkout , name="checkout"),
    path('transaction/' , update_transaction_records, name="train"),

]

src/main/urls.py
from django.contrib import admin
from django.urls import path , include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('account/', include('account.urls') ),
    path('cart/', include('cart.urls') ),
    path('profile/', include('userprofile.urls') ),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path , include
from products.views import product_list

app_name = 'products'

urlpatterns = [
    path('list/' , product_list , name = 'product_list'),
]

src/cart/models.py
from django.db import models
from userprofile.models import Profile
from products.models import Product
# Create your models here.

class OrderItem(models.Model):
    owner           = models.ForeignKey(Profile , on_delete=models.CASCADE)
    product         = models.ForeignKey(Product , on_delete=models.SET_NULL ,null = True)
    is_ordered      = models.BooleanField(default=False)
    date_added      = models.DateTimeField(auto_now=True)
    date_ordered    = models.DateTimeField(null=True)

    objects         = models.Manager()

    def __str__(self):
        return self.product.name


class Order(models.Model):
    owner           = models.ForeignKey(Profile , on_delete=models.SET_NULL , null = True)
    is_ordered      = models.BooleanField(default=False)
    items           = models.ManyToManyField(OrderItem)
    date_ordered    = models.DateTimeField(auto_now=True)

    objects         = models.Manager()

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.product.price for item in self.items.all()]) 

    def __str__(self):
        return self.owner.name + "  \t  " + self.owner.user.email


class Transaction(models.Model):
    profile     = models.ForeignKey(Profile , on_delete=models.SET_NULL , null= True)
    order_id    = models.CharField(max_length=120)
    amount      = models.DecimalField(max_digits=64, decimal_places=2)
    success     = models.BooleanField(default=True)
    timestamp   = models.DateTimeField(auto_now_add=True )

    objects = models.Manager()

    def __str__(self):
        return self.order_id

    class Meta:
        ordering = ['-timestamp']

src/cart/views.py
from django.shortcuts import render ,redirect ,get_object_or_404 
from userprofile.models import Profile
from products.models import Product
from cart.models import Order , OrderItem , Transaction
from django.contrib import messages
import datetime


def get_user_pending_order(request):
    profile = get_object_or_404(Profile,user=request.user)
    order   = Order.objects.filter(owner=profile , is_ordered=False)
    if order.exists():
        return order[0]
    return 0

def add_to_cart(request , **kwargs):
    context = {}
    # get User Profile
    profile = get_object_or_404(Profile, user=request.user)
    #filtered by produc id
    product = Product.objects.filter(pk=kwargs.get('item_id' , "")).first()
    
    #create order item 
    order_item , status = OrderItem.objects.get_or_create(product = product,owner=profile)
    # create order associated with user
    user_order, status = Order.objects.get_or_create(owner=profile)
    if order_item.owner.user.email == user_order.owner.user.email:
        user_order.items.add(order_item)
    
    if status:
        user_order.save()
    
    messages.info(request, "Item added to Cart ")
    return redirect('products:product_list')

def order_details(request):
    context = {}
    orders = get_user_pending_order(request)
    context['orders'] = orders
    return render(request,'cart/order_summary.html' , context)

def delete_from_cart(request , item_id):
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    
    # print(item_to_delete.owner.user.email)
    if item_to_delete.exists():
        delete_item = item_to_delete[0]

        if request.user.email == delete_item.owner.user.email:
            delete_item.delete()
            messages.info(request,"Your item has been deleted from cart")
    
    return redirect('cart:order_summary')

def checkout(request):
    existing_order = get_user_pending_order(request)
    context = {
        'order' : existing_order
    }
    return render(request, 'cart/new_checkout.html' , context)

def update_transaction_records(request):
    #pulling out order
    order_to_purchase = get_user_pending_order(request)
    order_to_purchase.is_ordered = True
    order_to_purchase.date_ordered = datetime.datetime.now()
    order_to_purchase.save()
    #pulled order updated and saved it by making some changes 

    #querring items list 
    order_items = order_to_purchase.items.all()

    #updating queried list all at once
    order_items.update(is_ordered= True ,date_ordered = datetime.datetime.now())

    user_profile = get_object_or_404(Profile, user=request.user)
    
    
    # get the products from the items
    # Yo chai list ekaichoti add garney tarika ho hai 
    #just for memo
    # order_products = [item.product for item in order_items]
    # user_profile.ebooks.add(*order_products)
    # user_profile.save()
    transaction = Transaction(profile=user_profile,
                            order_id=order_to_purchase.id,
                            amount=order_to_purchase.get_cart_total(),
                            success=True)

    transaction.save()

    messages.info(request,"Thank You from buying from our site")
    return redirect('userprofile:profile')

src/cart/templates/cart/new_checkout.html
<div class="col-md-8 col-xs-12">
    <table class="table">
      <tr>
        <td><h4>Order Summary</h4></td>
      </tr>
      <tr>
        <td>
          {% for item in order.get_cart_items %}
            <tr>
              <td>{{ item }}</td>
              <td>${{ item.product.price }}</td>
            </tr>
          {% endfor %}
        </td>
      </tr>
      <tr>
        <td><strong>Order Total</strong> </td>
        <td> <strong>${{ order.get_cart_total }}</strong></td>
      </tr>
    </table>
    <a href = "{% url 'cart:train' %}">
    <button  class="btn btn-warning" style="width: 100%;">Buy</button>
    </a>
</div>

src/cart/templates/cart/order_summary.html
{% extends 'base.html' %}


{% block content %}

<section>
    <div class = "row">
        <table class ="table table-hover table-bordered text-center">
            <tr class = "text-center">
                <th>no.</th>
                <th>Item</th>
                <th>Price</th>
            </tr>
            {% for item in orders.get_cart_items %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td> {{ item.product.name }}
                    <span class="pull-right">
                        <a href="{% url 'cart:delete' item.id %}" 
                        data-balloon="remove this item from cart" class="text-danger" 
                        onclick="return confirm_delete();">
                        delete
                        </a>
                    </span>
                    </td>
                    <td> {{ item.product.price }}
                  
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan=3>You dont have any items</td>
                </tr>
            {% endfor %}

            <tr>
                {% if orders.get_cart_total != None %}
                <td colspan=2>
                    <strong class = "pull-right">Order Total</strong>
                </td>
                <td colspan=1>
                    $<strong>{{ orders.get_cart_total }}</strong>
                </td>
                {% endif %}
            </tr>

            <tr>
                <td colspan=1>
                    <a href="{% url 'products:product_list' %}" class="btn btn-warning pull-left">
                        {% if orders %}Continue Shopping{% else %}Add Items to Cart {% endif %}
                    </a> 
                </td>
                <td colspan=2>
                    {% if orders.get_cart_items %}
                      <a href="{% url 'cart:checkout'  %}" class="pull-right btn btn-primary">Proceed To Checkout</a>
                    {% endif %}
                </td>
            </tr>


        </table>
    </div>
</section>

{% endblock content %}


{% block scripts %}
{{ block.super }}
  <script>
  function confirm_delete(){
    return confirm("Do you want to remove this item from cart?");
  }
  </script>
{% endblock scripts %}