src/cart/urls.py
from django.urls import path 

from cart.views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    update_transaction_records,
    # success
)

app_name = 'cart'

urlpatterns = [
    path('addtocart/<int:item_id>' , add_to_cart , name="add_to_cart"),
    path('ordersummary' , order_details , name="order_summary"),
    path('delete/<int:item_id>' , delete_from_cart , name="delete"),
    path('checkout/' , checkout , name="checkout"),
    path('transaction/' , update_transaction_records, name="train"),

]

src/main/urls.py
from django.contrib import admin
from django.urls import path , include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('account/', include('account.urls') ),
    path('cart/', include('cart.urls') ),
    path('profile/', include('userprofile.urls') ),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path , include
from products.views import product_list

app_name = 'products'

urlpatterns = [
    path('list/' , product_list , name = 'product_list'),
]

src/userprofile/urls.py
from django.urls import path , include
from userprofile.views import my_profile

app_name = 'userprofile'

urlpatterns = [
    path('list/' , my_profile , name = 'profile'),
]

src/userprofile/models.py
from django.db import models
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import post_delete


def upload_location(instance , filename , **kwargs):
    file_path = 'blog/{user_id}/{name}- {filename}'.format(
        user_id      = str(instance.user.id),
        name         = str(instance.name),
        filename     = filename
    )

    return file_path
    


class Profile(models.Model):
    user                    = models.OneToOneField(settings.AUTH_USER_MODEL , on_delete=models.CASCADE)
    name                    = models.CharField(max_length=60)
    contact                 = models.CharField(max_length=15)
    date_of_birth           = models.DateField(verbose_name="birth date",blank = False);
    image                   = models.ImageField(upload_to = upload_location ,default = 'download.png')

    objects = models.Manager()

    def __str__(self):
        return self.name

@receiver(post_delete, sender = Profile)
def submission_delete(sender , instance , **kwargs):
    instance.image.delete(False)

src/userprofile/views.py
from django.shortcuts import render
from userprofile.models import Profile
from cart.models import Order
from django.contrib.auth.decorators import login_required
# Create your views here.


def my_profile(request):
	my_user_profile = Profile.objects.filter(user=request.user).first()
	my_orders = Order.objects.filter(is_ordered=True, owner=my_user_profile)
	context = {
		'my_orders': my_orders
	}

	return render(request, "userprofile/profile.html", context)

src/userprofile/templates/userprofile/profile.html
{% extends 'base.html' %}

{% block content %}

<table class="table table-hover table-bordered text-center">
      <tr class="text-center">
        <th>Date Ordered</th>
        <th>Reference Code</th>
        <th>Items</th>
        <th>Price</th>
      </tr>
      {% for order in my_orders %}
        <tr>
          <td>{{ order.date_ordered }}</td>
          <td>{{ order.ref_code }}</td>
          <td>
        	{% for item in order.items.all %}
        		{{ item.product.name }}
      		{% endfor %}
      	  </td>
          <td>${{ order.get_cart_total }}</td>

        </tr>
      {% empty %}
        <tr>
          <td colspan= 4> You have no orders.</td>
        </tr>
      {% endfor %}

      <tr>
        <td colspan=4>
          <a href="{% url 'products:product_list' %}" class="btn btn-warning pull-left">
            {% if not order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
          </a> 
        </td>
      </tr>
    </table>

{% endblock content %}